# in windows environment
* make sure you have a complete gtk+3.0 development environment.
* if not ,you can find gtk+3.0-all-in-one-bundle in the gtk official website.
* add necessary files into C::B's link file and search directories, then just build it.
* i'll add the makefile some day, but not now. I'm tired.
* after building the files, make sure the .ui files and the "img" folder are in the same directory with the binary file.

#  in linux environment
* simply run make
* if you wabt to clear the directory, run make clean
* the files will generatre in build/
